version: '3'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: mcp-base

  cp:
    build:
      context: .
      dockerfile: CP/Dockerfile
    image: mcp-cp
    depends_on:
      - base
    volumes:
      - .:/app
      - ./res:/app/res

  sat:
    build:
      context: .
      dockerfile: SAT/Dockerfile
    image: mcp-sat
    depends_on:
      - base
    volumes:
      - ./res:/app/res

  smt:
    build:
      context: .
      dockerfile: SMT/Dockerfile
    image: mcp-smt
    depends_on:
      - base
    volumes:
      - ./res:/app/res

  mip:
    build:
      context: .
      dockerfile: MIP/Dockerfile
    volumes:
      - .:/app
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - base